theme: jekyll-theme-slate

docs_list_title: ACME Documentation
docs:

- title: About
  url: About.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
  
<h2>{{ site.data.samplelist.docs_list_title }}</h2>
<ul>
   {% for item in site.data.samplelist.docs %}
      <li><a href="{{ item.url }}">{{ item.title }}</a></li>
   {% endfor %}
</ul>
